httpPort: 7100
mongodbUrl: mongodb://localhost:27017/srd-lps3
mongoMainDatabase: srd-lps3
#uiPath: E:/gitrepo/seer-ui/level2/dist-lps3new
uiPath: E:/gitrepo/seer-ui/custom/lps3-stats/dist
commAdapterIO: Http
vehicleSimulation: Http
#startFromDB: false

operator:
  signIn: true
myLifts:
  - name: lift1
    host: 127.0.0.1
    port: 504
    open1: 0
    open2: 1
    floor1: 16
    floor2: 18
    inPlace: 17

# 设备服务器配置项
synchronizer:
  # 电梯服务器地址
  liftRoute: http://localhost:7100/api/
  # 门服务器地址
  doorRoute: http://localhost:7100/api/

#
#doors:
#  T1:
#    host: 221.7.94.51         # 电控柜的IP
#    port: 502               # 端口号 默认为 502
#    openAddr: 1280          # 控制开门的地址 默认为 1280
#    closeAddr: 1280         # 控制关门的地址 默认为 1281
#    feedback: false          # true: 这是个有开门到位信号的自动门， false: 这个门没有开门到位反馈
#    delayForOpened: 1         # 一定次数后，设置自动门状态为OPEN，当 feedback = false 时有效
#    delayForCancelOpen: 500   # 一段时间后取消写入开门信号，单位为 ms    0: 不清空
#    delayForCancelClose: 500  # 一段时间后取消写入关门信号，单位为 ms    0: 不清空
#  T2:
#    host: 221.7.94.34        # 电控柜的IP
#    port: 502               # 端口号 默认为 502
#    unitId: 1
#    openAddr: 1280          # 控制开门的地址 默认为 1280
#    closeAddr: 1280         # 控制关门的地址 默认为 1281
#    feedback: false          # true: 这是个有开门到位信号的自动门， false: 这个门没有开门到位反馈
#    delayForOpened: 1         # 一定次数后，设置自动门状态为OPEN，当 feedback = false 时有效
#    delayForCancelOpen: 500   # 一段时间后取消写入开门信号，单位为 ms    0: 不清空
#    delayForCancelClose: 500  # 一段时间后取消写入关门信号，单位为 ms    0: 不清空