httpPort: 7100
mongodbUrl: mongodb://localhost:27017/srd-moshi
mongoMainDatabase: srd-moshi
commAdapterIO: Http
vehicleSimulation: Http
uiPath: E:/gitRepo/seer-ui/level2/dist-moshi
#startFromDB: false
twinkle: 500
interval: 5
#others:
#  - MD2-01
#  - Plating-01
operator:
  orders:
    - menuId: transfer
      label: 栈板运输任务
      menuItemBackground: "#0066cc"
      menuItemTextColor: white
      robotTaskDef: transfer
      tip: 栈板运输任务
      confirmMessage: 确定下发栈板运输任务吗？
      params:
        - name: from
          input: selectField
          label: 起点
          options: &op
            - value: MD2-01
              label: MD2-01
            - value: MD2-02
              label: MD2-02
            - value: MD2-03
              label: MD2-03
            - value: T-MD2-01
              label: T-MD2-01
            - value: MD5-01
              label: MD5-01
            - value: MD5-02
              label: MD5-02
            - value: MD5-03
              label: MD5-03
            - value: MD5-04
              label: MD5-04
            - value: MD5-05
              label: MD5-05
            - value: MD6-01
              label: MD6-01
            - value: MD6-02
              label: MD6-02
            - value: MD6-03
              label: MD6-03
            - value: MD6-04
              label: MD6-04
            - value: MD6-05
              label: MD6-05
            - value: MD6-06
              label: MD6-06
            - value: 102-01
              label: 102-01
            - value: 102-02
              label: 102-02
            - value: 102-03
              label: 102-03
            - value: 102-04
              label: 102-04
            - value: 102-05
              label: 102-05
            - value: 102-06
              label: 102-06
            - value: 102-07
              label: 102-07
            - value: 102-08
              label: 102-08
            - value: 102-09
              label: 102-09
            - value: 102-10
              label: 102-10
            - value: T-102-01
              label: T-102-01
            - value: 103-01
              label: 103-01
            - value: 103-02
              label: 103-02
            - value: 103-03
              label: 103-03
            - value: 103-04
              label: 103-04
            - value: 103-05
              label: 103-05
            - value: 103-06
              label: 103-06
            - value: 103-07
              label: 103-07
            - value: 103-08
              label: 103-08
            - value: 102-09
              label: 102-09
            - value: T-103-01
              label: T-103-01
            - value: Plating-01
              label: Plating-01
            - value: Plating-02
              label: Plating-02
            - value: Plating-03
              label: Plating-03
            - value: Plating-04
              label: Plating-04
            - value: Plating-05
              label: Plating-05
            - value: T-Plating-01
              label: T-Plating-01
            - value: Stamping-01
              label: Stamping-01
            - value: Stamping-02
              label: Stamping-02
            - value: Stamping-03
              label: Stamping-03
            - value: Stamping-04
              label: Stamping-04
            - value: Stamping-05
              label: Stamping-05
            - value: T-Stamping-01
              label: T-Stamping-01
            - value: T-Stamping-02
              label: T-Stamping-02
            - value: T-Stamping-03
              label: T-Stamping-03

        - name: to
          input: selectField
          label: 终点库区
          options:
            - value: 102平台
              label: 102平台
            - value: 注塑平台1
              label: 注塑平台1
            - value: MD2
              label: MD2
            - value: MD5
              label: MD5
            - value: MD6
              label: MD6
            - value: Stamping
              label: Stamping
            - value: Plating
              label: Plating

    - menuId: updateSite
      label: 更新报错库位
      menuItemBackground: "#ff2626"
      menuItemTextColor: white
      robotTaskDef: updateSite
      tip: 更新报错库位
      confirmMessage: 确定更新库位信息吗?
      params:
        - name: type
          input: select
          label: 选择库位类型
          options:
            - value: default
              label: -----
            - value: from
              label: 发货库位
            - value: to
              label: 收货库位
        - name: siteId
          input: selectField
          label: 库位
          options: *op
areaToCabinet:
  area1:
#    host: 192.168.1.5
    host: 127.0.0.1
    port: 502
    siteIdToAddress:
      MD2-01:
        index: 0
        green: 1280
        yellow: 1281
        red: 1282
        sensor1: 1024
        sensor2: 1025
      T-Plating-01:
        index: 1
        green: 1283
        yellow: 1284
        red: 1285
        sensor1: 1026
        sensor2: 1027
      T-MD2-01:
        index: 2
        green: 1286
        yellow: 1287
        red: 1288
        sensor1: 1028
        sensor2: 1029
#  area2:
##    host: 192.168.1.5
#    host: 127.0.0.1
#    port: 504
#    siteIdToAddress:
#      Plating-01:
#        green: 1280
#        yellow: 1281
#        red: 1282
#        sensor1: 1024
#        sensor2: 1025
#      T-Plating-01:
#        red: 1290
#        yellow: 1291
#        green: 1292
#        sensor1: 1034
#        sensor2: 1035